//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigSystem
    {
        public long Id { get; set; }
        public string Logo { get; set; }
        public string Address { get; set; }
        public string IdNo { get; set; }
        public string Phone { get; set; }
        public string Hotline1 { get; set; }
        public string Hotline2 { get; set; }
        public string Description { get; set; }
        public string TitleDefault { get; set; }
        public string Infomation { get; set; }
    }
}
