//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentOfExpense
    {
        public long Id { get; set; }
        public Nullable<long> TypeOfPaymentId { get; set; }
        public Nullable<decimal> Money { get; set; }
        public string Reason { get; set; }
        public string Bill { get; set; }
        public string Accreditative { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual TypeOfPayment TypeOfPayment { get; set; }
    }
}
